<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timberslide.proto

namespace Ts;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Event extends \Google\Protobuf\Internal\Message
{
    private $Topic = '';
    private $Message = '';
    private $Done = false;

    public function getTopic()
    {
        return $this->Topic;
    }

    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->Topic = $var;
    }

    public function getMessage()
    {
        return $this->Message;
    }

    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->Message = $var;
    }

    public function getDone()
    {
        return $this->Done;
    }

    public function setDone($var)
    {
        GPBUtil::checkBool($var);
        $this->Done = $var;
    }

}

class EventReply extends \Google\Protobuf\Internal\Message
{

}

class Topic extends \Google\Protobuf\Internal\Message
{
    private $ID = 0;
    private $Name = '';
    private $Position = 0;

    public function getID()
    {
        return $this->ID;
    }

    public function setID($var)
    {
        GPBUtil::checkInt64($var);
        $this->ID = $var;
    }

    public function getName()
    {
        return $this->Name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;
    }

    public function getPosition()
    {
        return $this->Position;
    }

    public function setPosition($var)
    {
        GPBUtil::checkInt64($var);
        $this->Position = $var;
    }

}

class Register extends \Google\Protobuf\Internal\Message
{
    private $Topic = '';
    private $User = '';

    public function getTopic()
    {
        return $this->Topic;
    }

    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->Topic = $var;
    }

    public function getUser()
    {
        return $this->User;
    }

    public function setUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->User = $var;
    }

}

class RegisterReply extends \Google\Protobuf\Internal\Message
{

}

class TopicsReq extends \Google\Protobuf\Internal\Message
{

}

class TopicsReply extends \Google\Protobuf\Internal\Message
{
    private $topics;

    public function getTopics()
    {
        return $this->topics;
    }

    public function setTopics(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Ts\Topic::class);
        $this->topics = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0af0030a1174696d626572736c6964652e70726f746f1202747322350a05" .
    "4576656e74120d0a05546f706963180120012809120f0a074d6573736167" .
    "65180220012809120c0a04446f6e65180320012808220c0a0a4576656e74" .
    "5265706c7922330a05546f706963120a0a024944180120012803120c0a04" .
    "4e616d6518022001280912100a08506f736974696f6e1803200128032227" .
    "0a085265676973746572120d0a05546f706963180120012809120c0a0455" .
    "736572180220012809220f0a0d52656769737465725265706c79220b0a09" .
    "546f7069637352657122280a0b546f706963735265706c7912190a06746f" .
    "7069637318012003280b32092e74732e546f70696332390a06496e676573" .
    "74122f0a0c53747265616d4576656e747312092e74732e4576656e741a0e" .
    "2e74732e4576656e745265706c7922002801300132310a0853747265616d" .
    "657212250a0947657453747265616d12092e74732e546f7069631a092e74" .
    "732e4576656e7422003001326b0a06546f7069637312320a0d7265676973" .
    "746572546f706963120c2e74732e52656769737465721a112e74732e5265" .
    "6769737465725265706c792200122d0a09676574546f70696373120d2e74" .
    "732e546f706963735265711a0f2e74732e546f706963735265706c792200" .
    "42090a0765782e67727063620670726f746f33"
));

